docker/Dockerfile
It wasn't clear to me whether we were catching all these, plus I think we were uninstalling ncurses-devel, so factor out and install them as the last step.
=> Make sure docker image contains all the desired devel packages

pep-513.rst
It seems like the discussion on distutils-sig has died down, so I tried to use some of the ideas discussed in #7 to make revisions to the PEP.
=> PEP Revisions

docker/Dockerfile, docker/build_scripts/build.sh, docker/build_scripts/build_utils.sh
Refactor some Dockerfile code into a couple of scripts.
Add builds of Python 2.6 and 3.3.
=> Refactor Dockerfile into component scripts

docker/Dockerfile-i686, docker/Dockerfile-x86_64, docker/build_scripts/build.sh
=> Add /usr/local/lib{64} to /etc/ld.so.conf by default

policy-info/distro-versions-info.txt
Just came across these and want to make sure I save the link somewhere
where we can find it when it's time to do manylinux2. Not sure what the
best place is, but this seems like a reasonable option?
=> Add a note about Distrowatch's amazing distro version tables

docker/build_scripts/build.sh
Cmake is a handy tool for development, and would be nice to have in base image
=> Add cmake28 package and symlink it to cmake

docker/build_scripts/build.sh, docker/build_scripts/build_utils.sh
=> add autoconf 2.69 to the image

docker/build_scripts/build.sh
=> Patch libc headers to make them compatible with C99 inline semantics

.travis.yml, docker/build_scripts/build.sh, docker/build_scripts/build_utils.sh, docker/deploy.sh
Also update to the latest bugfix release of Python 3.5, 3.4 and 2.7.
Closes #82.
=> Add Python 3.6

docker/build_scripts/build.sh
These were released on January 17th.
=> Update to Python 3.4.6 and Python 3.5.3

docker/build_scripts/build.sh
Also switched the IP address for the DNS name to avoid any future surprises. Fixes #103
Credit for this fix goes out to Ryan Walker (@ryandub) and Lars Butler (@larsbutler).
=> Reference specific 5.11 release instead of version 5

docker/build_scripts/build.sh
https://www.openssl.org/news/secadv/20171207.txt
=> Update OpenSSL to address security fix.

docker/build_scripts/build.sh
Check hashes of SQLite and patchelf. Also update to new versions.
=> Check hashes of SQLite and patchelf

README.rst, docker/build_scripts/build.sh, docker/build_scripts/build_utils.sh
If nothing breaks, might be a good idea to do this to benefit from any security fixes.
=> Update CPython versions to the latest at time of writing

docker/build_scripts/ssl-check.py
(Forgot to remove in my last PR, sorry.)
=> Remove leftover relic from supporting CPython 2.6.

docker/build_scripts/build_env.sh
Update CPython 2.7 from 2.7.14 to 2.7.15
=> Update CPython 2.7 from 2.7.14 to 2.7.15

docker/build_scripts/build_env.sh
many bug fixes including CVE.
c.f. https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-7-final
c.f. https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-1-final
=> Update from Python 3.6.6, 3.7.0 to 3.6.7, 3.7.1

docker/build_scripts/build_env.sh
many bug fixes.
c.f. https://docs.python.org/3.6/whatsnew/changelog.html#python-3-6-8-final
c.f. https://docs.python.org/3.7/whatsnew/changelog.html#python-3-7-2-final
=> Update from Python 3.6.7, 3.7.1 to 3.6.8, 3.7.2

docker/build_scripts/build.sh, docker/glibc/Dockerfile
Size is reduced by about 200MB
Rework locale archive (size can grow substantially, at least with a glibc update)
Get rid of unused man files & locales from devtoolset-8 and custom built tools
=> Reduce image size

docker/build_scripts/py36-requirements.txt
=> Update auditwheel to 2.1.0 (manylinux1 branch)

docker/build_scripts/build_env.sh
Update git from 2.21.0 to 2.23.0
=> Update git from 2.21.0 to 2.23.0

docker/build_scripts/build_env.sh
Update git from 2.21.0 to 2.23.0 (manylinux1)
=> Update git from 2.21.0 to 2.23.0 (manylinux1)

docker/build_scripts/build.sh
fix urls to use https instead of http
=> fixes broken urls due to upstream changes

docker/build_scripts/build_env.sh
update the version and also try to document the supported format for the next release cycle
=> update for cpython 3.8.0 final

docker/build_scripts/build_env.sh
manylinux1 branch PR cherry-picking commit from #373
=> Update CPython 3.7 from 3.7.4 to 3.7.5

docker/build_scripts/build_env.sh
Fix security issues. [Full change log](https://raw.githubusercontent.com/python/cpython/c2f86d86e6c8f5fd1ef602128b537a48f3f5c063/Misc/NEWS.d/2.7.17rc1.rst).
=> Update CPython 2.7 from 2.7.16 to 2.7.17

docker/build_scripts/build_env.sh
Release notes: https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-9
=> Update CPython 3.5 from 3.5.7 to 3.5.9

docker/build_scripts/build_env.sh
=> Update CPython 3.5 from 3.5.7 to 3.5.9 (manylinux1)

README.rst
xref [this comment](https://github.com/pypa/manylinux/issues/338#issuecomment-558500000) in gh-338 where it was suggested to catalogue all available images.
=> List all currently available docker images

docker/build_scripts/py37-requirements.txt
cherry-pick from master branch
=> Update pyelftools from 0.25 to 0.26

docker/build_scripts/build_env.sh
- Update CPython 3.6 from 3.6.9 to 3.6.10
- Update CPython 3.7 from 3.7.5 to 3.7.6
- Update CPython 3.8 from 3.8.0 to 3.8.1
=> Update CPython (manylinux1)

docker/build_scripts/build_env.sh
- Update CPython 3.6 from 3.6.9 to 3.6.10
- Update CPython 3.7 from 3.7.5 to 3.7.6
- Update CPython 3.8 from 3.8.0 to 3.8.1
=> Update CPython (manylinux2014)

docker/deploy.sh
=> Manylinux1 - build tags

docker/deploy.sh
Port of #440 for manylinux2014
=> Manylinux2014 - build tags

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/release/3.8.2/whatsnew/changelog.html#python-3-8-2-final
=> [manylinux1] Update CPython 3.8 from 3.8.1 to 3.8.2

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/release/3.8.2/whatsnew/changelog.html#python-3-8-2-final
=> [manylinux2010] Update CPython 3.8 from 3.8.1 to 3.8.2

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/release/3.8.2/whatsnew/changelog.html#python-3-8-2-final
=> [manylinux2014] Update CPython 3.8 from 3.8.1 to 3.8.2

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/release/3.7.7/whatsnew/changelog.html#python-3-7-7-final
=> [manylinux1] Update CPython 3.7 from 3.7.6 to 3.7.7

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/release/3.7.7/whatsnew/changelog.html#python-3-7-7-final
=> [manylinux2010] Update CPython 3.7 from 3.7.6 to 3.7.7

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/release/3.7.7/whatsnew/changelog.html#python-3-7-7-final
=> [manylinux2014] Update CPython 3.7 from 3.7.6 to 3.7.7

README.rst, docker/build_scripts/build_env.sh, docker/build_scripts/build_utils.sh, docker/build_scripts/py37-requirements.txt
=> redo gh-497 for manylinux2014

build.sh, docker/build_scripts/build.sh, docker/build_scripts/build_env.sh, docker/build_scripts/build_utils.sh
=> [manylinux1] Update OpenSSL from 1.0.2u to 1.1.1e

docker/build_scripts/build_env.sh
=> [manylinux2010] Update OpenSSL from 1.1.1e to 1.1.1f

docker/build_scripts/build_env.sh
=> [manylinux1] Update OpenSSL from 1.1.1e to 1.1.1f

docker/build_scripts/build_env.sh
=> [manylinux1] Update OpenSSL from 1.1.1f to 1.1.1g

docker/build_scripts/build_env.sh
change log: https://github.com/python/cpython/blob/v2.7.18/Misc/NEWS.d/2.7.18rc1.rst
=> [manylinux1] Update CPython 2.7 from 2.7.17 to 2.7.18

docker/build_scripts/build_env.sh
change log: https://github.com/python/cpython/blob/v2.7.18/Misc/NEWS.d/2.7.18rc1.rst
=> Update CPython 2.7 from 2.7.17 to 2.7.18

docker/build_scripts/build_env.sh
https://curl.haxx.se/changes.html
=> Update curl from 7.69.1 to 7.70.0

docker/build_scripts/build_env.sh
Changelog: https://github.com/python/cpython/blob/v3.8.3/Misc/NEWS.d/3.8.3.rst
=> [manylinux1] Update CPython 3.8 from 3.8.2 to 3.8.3

docker/build_scripts/build_env.sh
Changelog: https://github.com/python/cpython/blob/v3.8.3/Misc/NEWS.d/3.8.3.rst
=> [manylinux2010] Update CPython 3.8 from 3.8.2 to 3.8.3

docker/build_scripts/build_env.sh
Changelog: https://github.com/python/cpython/blob/v3.8.3/Misc/NEWS.d/3.8.3.rst
=> [manylinux2014] Update CPython 3.8 from 3.8.2 to 3.8.3

.travis.yml, build.sh, docker/glibc/Dockerfile, docker/glibc/Dockerfile-i686, docker/glibc/Dockerfile-x86_64, docker/glibc/build.sh, travis-ci/cache_images.sh, travis-ci/load_cached_images.sh, travis-ci/tags.sh
Fixes #561: this change fixes installing i686 packages into
manylinux2010_x86_64 image.
Also, it reworks Travis setup slightly, since x86_64 and i686 glibc
builds should run in different stages in order to avoid timeouts.
=> Build i686 glibc

docker/build_scripts/build_env.sh, docker/build_scripts/build_utils.sh
https://www.python.org/downloads/release/python-390b3/
https://www.python.org/dev/peps/pep-0596/
Fixes #482.
=> Add CPython 3.9.0b3

docker/build_scripts/build_env.sh, docker/build_scripts/build_utils.sh
Cherry-picked 41cc63f620f61f9b2afafba9b837eb58a02ae11c onto manylinux1 branch
=> [manylinux1] Add CPython 3.9.0b3

docker/build_scripts/build_env.sh, docker/build_scripts/build_utils.sh
Cherry-picked 41cc63f620f61f9b2afafba9b837eb58a02ae11c onto manylinux2014 branch
Closes #629 (together with #639)
=> [manylinux2014] Add CPython 3.9.0b3

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.6.11/whatsnew/changelog.html
* https://docs.python.org/release/3.7.8/whatsnew/changelog.html
=> [manylinux2014] CPython 3.6.10 → 3.6.11 & 3.7.7 → 3.7.8

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.6.11/whatsnew/changelog.html
* https://docs.python.org/release/3.7.8/whatsnew/changelog.html
=> [manylinux2010] CPython 3.6.10 → 3.6.11 & 3.7.7 → 3.7.8

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.6.11/whatsnew/changelog.html
* https://docs.python.org/release/3.7.8/whatsnew/changelog.html
=> [manylinux1] CPython 3.6.10 → 3.6.11 & 3.7.7 → 3.7.8

docker/build_scripts/build_env.sh
Changelog:
* https://docs.python.org/release/3.8.4/whatsnew/changelog.html#changelog
=> [manylinux1] CPython 3.8.3 → 3.8.4

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.8.4/whatsnew/changelog.html#changelog
=> [manylinux2014] CPython 3.8.3 → 3.8.4

docker/build_scripts/build_env.sh
Changelog:
* https://docs.python.org/release/3.8.4/whatsnew/changelog.html#changelog
=> [manylinux2010] CPython 3.8.3 → 3.8.4

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.8.5/whatsnew/changelog.html
* https://docs.python.org/3.9/whatsnew/changelog.html
=> [manylinux2014] CPython 3.8.4 → 3.8.5 & 3.9.0b3 → 3.9.0b5

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.8.5/whatsnew/changelog.html
* https://docs.python.org/3.9/whatsnew/changelog.html
=> [manylinux1] CPython 3.8.4 → 3.8.5 & 3.9.0b3 → 3.9.0b5

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.8.5/whatsnew/changelog.html
* https://docs.python.org/3.9/whatsnew/changelog.html
=> [manylinux2010] CPython 3.8.4 → 3.8.5 & 3.9.0b3 → 3.9.0b5

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/3.9/whatsnew/3.9.html
=> [manylinux2010] CPython 3.9.0b5 → 3.9.0rc1

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/3.9/whatsnew/3.9.html
=> [manylinux1] CPython 3.9.0b5 → 3.9.0rc1

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.6.12/whatsnew/changelog.html
* https://docs.python.org/release/3.7.9/whatsnew/changelog.html
=> [manylinux2014] CPython 3.6.11 → 3.6.12 & 3.7.8 → 3.7.9

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.6.12/whatsnew/changelog.html
* https://docs.python.org/release/3.7.9/whatsnew/changelog.html
=> [manylinux2010] CPython 3.6.11 → 3.6.12 & 3.7.8 → 3.7.9

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.5.10/whatsnew/changelog.html
* https://docs.python.org/release/3.9.0rc2/whatsnew/changelog.html
=> [manylinux1] CPython 3.5.9 → 3.5.10 & 3.9.0rc1 → 3.9.0rc2

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.5.10/whatsnew/changelog.html
* https://docs.python.org/release/3.9.0rc2/whatsnew/changelog.html
=> [manylinux2014] CPython 3.5.9 → 3.5.10 & 3.9.0rc1 → 3.9.0rc2

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.5.10/whatsnew/changelog.html
* https://docs.python.org/release/3.9.0rc2/whatsnew/changelog.html
=> [manylinux2010] CPython 3.5.9 → 3.5.10 & 3.9.0rc1 → 3.9.0rc2

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/3/whatsnew/changelog.html#python-3-8-6-final
=> [manylinux2014] CPython 3.8.5 → 3.8.6

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/3/whatsnew/changelog.html#python-3-8-6-final
* https://www.openssl.org/news/cl111.txt
=> [manylinux1] CPython 3.8.5 → 3.8.6 & OpenSSL 1.1.1g → 1.1.1h

README.rst, docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/3.9/whatsnew/changelog.html
=> [manylinux1] CPython 3.9.0rc2 → 3.9.0

README.rst, docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/3.9/whatsnew/changelog.html
=> [manylinux2010] CPython 3.9.0rc2 → 3.9.0

README.rst, docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/3.9/whatsnew/changelog.html
=> [manylinux2014] CPython 3.9.0rc2 → 3.9.0

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/3/whatsnew/changelog.html#python-3-9-1-final
* https://www.openssl.org/news/cl111.txt
=> [manylinux2010] CPython 3.9.0 → 3.9.1 & OpenSSL 1.1.1h → 1.1.1i

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/3/whatsnew/changelog.html#python-3-9-1-final
* https://www.openssl.org/news/cl111.txt
=> [manylinux1] CPython 3.9.0 → 3.9.1 & OpenSSL 1.1.1h → 1.1.1i

docker/build_scripts/build.sh
Do not update epel-release package for now
c.f. nealef/clefos#5
=> [manylinux2014] workaround mirror issue on s390x

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/3/whatsnew/changelog.html#python-3-9-1-final
=> [manylinux2014] CPython 3.9.0 → 3.9.1

docker/build_scripts/build.sh
This reverts commit f6c6ee3a58fbda127fb8538cd10bfde2771e270d now that nealef/clefos#5 is fixed.
=> Revert "[manylinux2014] workaround mirror issue on s390x (#868)"

docker/build_scripts/requirements-tools.txt
`auditwheel` now vendors `wheel`
=> [manylinux2014] Drop wheel requirement in requirements-tools.txt

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-7-final
=> [manylinux1] CPython 3.8.6 → 3.8.7

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-7-final
=> [manylinux2010] CPython 3.8.6 → 3.8.7

docker/build_scripts/build_env.sh
Changelog: https://docs.python.org/3.8/whatsnew/changelog.html#python-3-8-7-final
=> [manylinux2014] CPython 3.8.6 → 3.8.7

docker/Dockerfile, docker/build_scripts/build_env_runtime.sh, docker/build_scripts/build_utils.sh, docker/build_scripts/install-libtool.sh, docker/build_scripts/install-runtime-packages.sh
Builds on top of #879 / #965 / #966
=> [manylinux2014] Split libtool build in runtime_base image

docker/Dockerfile, docker/build_scripts/build-cmake.sh, docker/build_scripts/build.sh, docker/build_scripts/build_env.sh, docker/build_scripts/build_utils.sh
Builds on top of #879 / #965 / #966 / #967 / #968
=> [manylinux2014] Split cmake build from build_base image

docker/Dockerfile, docker/build_scripts/build-swig.sh
Builds on top of #879 / #965 / #966 / #967 / #968 / #969 / #970 / #971 / #972 / #973 / #974 / #975
Fix #659
=> [manylinux2014] Add swig

docker/Dockerfile
Builds on top of #879 / #965 / #966 / #967 / #968 / #969 / #970 / #971 / #972 / #973 / #974 / #975 / #976 / #977
=> [manylinux2014] Update automake from 1.16.2 to 1.16.3

.github/workflows/build.yml
This should be the only thing impacting docker cache.
=> Use a hash of the docker folder as a key to GHA cache

docker/Dockerfile
Changelogs:
* https://docs.python.org/release/3.8.8/whatsnew/changelog.html
* https://docs.python.org/release/3.9.2/whatsnew/changelog.html
=> CPython 3.8.{7→8} & 3.9.{1→2}

docker/build_scripts/build-sqlite3.sh, tests/run_tests.sh
=> Fix _sqlite3 missing on CPython 3.7+ on manylinux2010

docker/build_scripts/build_env.sh
See https://docs.python.org/release/3.9.4/whatsnew/changelog.html#changelog
=> [manylinux1] Update CPython 3.9.3 -> 3.9.4

docker/Dockerfile
See https://docs.python.org/release/3.9.4/whatsnew/changelog.html#changelog
=> Updated CPython 3.9.3 -> 3.9.4

docker/build_scripts/build_env.sh
Changelogs:
* https://docs.python.org/release/3.8.10/whatsnew/changelog.html
* https://docs.python.org/release/3.9.5/whatsnew/changelog.html
=> [manylinux1] Update CPython 3.8.{9→10} & 3.9.{4→5}

docker/Dockerfile
Changelogs:
* https://docs.python.org/release/3.8.10/whatsnew/changelog.html
* https://docs.python.org/release/3.9.5/whatsnew/changelog.html
=> Update CPython 3.8.{9→10} & 3.9.{4→5}

docker/build_scripts/install-runtime-packages.sh
=> [manylinux2010] Fix no package `hostname` available

docker/build_scripts/build.sh, docker/build_scripts/requirements-tools.txt
=> [manylinux1] Add pipx

travisci-install-buildx.sh
Issue with let's encrypt SSL certificate expired for https://oplab9.parqtec.unicamp.br
Let's go insecure & check sha256 sums
=> ci: fix docker installation on Travis CI ppc64le

docker/Dockerfile
- CPython 3.6.13 → 3.6.14: https://docs.python.org/release/3.6.14/whatsnew/changelog.html#changelog
- CPython 3.7.10 → 3.7.11: https://docs.python.org/release/3.7.11/whatsnew/changelog.html#changelog
- CPython 3.8.10 → 3.8.11: https://docs.python.org/release/3.8.11/whatsnew/changelog.html#changelog
- CPython 3.9.5 → 3.9.6: https://docs.python.org/release/3.9.6/whatsnew/changelog.html#changelog
- CPython 3.10.0b2 → 3.10.0b3: https://docs.python.org/3.10/whatsnew/changelog.html#python-3-10-0-beta-3
- SQLite 3.35.5 → 3.36.0: https://www.sqlite.org/changes.html#version_3_36_0
- git 2.31.1 → 2.32.0: https://github.com/git/git/blob/master/Documentation/RelNotes/2.32.0.txt
=> chore: update dependencies

docker/Dockerfile, docker/build_scripts/install-libxcrypt.sh
changelog: https://github.com/besser82/libxcrypt/blob/v4.4.23/NEWS
=> chore: libxcrypt 4.4.17 → 4.4.23

docker/build_scripts/build-cpython.sh
=> feature: keep CPython test modules

build.sh, travisci-install-buildx.sh
multiple fixes/updates for Travis CI builds.
=> fix(CI): fix arm64 builds on Travis CI

.github/workflows/build.yml, .github/workflows/update-dependencies.yml, .travis.yml, README.rst
=> chore: change references from `master`  to `main`

docker/build_scripts/finalize.sh
This reverts commit 5633492d84c4e918d2341ca5c421aff8836c7fe8.
=> Revert "Install cmake with apk on musllinux"

.travis.yml
This should at least help get rid of the 10 minutes with no output issue on ppc64le.
=> chore: output stats about builder every 30s on travis-ci

README.rst
Mark manylinux1 has unsupported in README
=> Mark manylinux1 has unsupported in README

.github/workflows/build.yml, README.rst, build.sh, docker/build_scripts/build-cpython.sh, docker/build_scripts/install-runtime-packages.sh
use gcc-toolset-12 on manylinux_2_28
=> feat: use gcc-toolset-12 on manylinux_2_28

docker/build_scripts/build-cpython.sh, tests/run_tests.sh
=> Fix build of _tkinter in Python 3.11 manylinux2014

.github/workflows/build.yml, .travis.yml, build.sh, docker/build_scripts/build-git.sh, docker/build_scripts/install-build-packages.sh, docker/build_scripts/install-entrypoint.sh, docker/build_scripts/install-runtime-packages.sh, docker/build_scripts/update-system-packages.sh, tests/run_tests.sh, travisci-install-buildx.sh
=> feature: add musllinux_1_2

README.rst
A bit of cleanup to the readme. I have trouble quickly finding the glibc to manylinux year conversion, this should help with that, along with a few fixes.
=> docs: 2014 supported, add glibc, compress list

.github/workflows/build.yml
We're hitting cache limits on GHA, just save the cache on main.
=> chore: split restore/save cache

.github/workflows/build.yml, .travis.yml, build.sh
=> feat: use GHA to build s390x/ppc64le images

.github/workflows/build.yml, .travis.yml
This reverts commit 7fccd9c3c38c5101dffdf5550899fd373d8a7377.
=> Revert "feat: use GHA to build s390x/ppc64le images"

README.rst, build.sh, docker/build_scripts/install-runtime-packages.sh
=> feat: update gcc-toolset to gcc-toolset-14 on manylinux_2_28

docker/build_scripts/finalize.sh, tests/run_tests.sh
=> fix: link `libstdc++` with `--as-needed` on `manylinux_2_{28,34}`

docker/build_scripts/finalize-one.sh
=> fix: remove setuptools when setting-up GraalPy
