pypa/manylinux

pep-513.rst

Fixes some grammatical errors and typos, particularly the egregious "Even if author or maintainers of a Python extension module with to use no external shared libraries"

Word salad

---

pep-513.rst

- Note why we are restricted to x86_64 and i386.
- Note explicitly that we aren't proposing any changes to
bdist_wheel (requested by Nick Coghlan)
- Slightly clarify the introduction to the Platform Detection section
- Add a note about manylinux2 being a thing that will probably exist
someday but that we're deferring for now (requested by Nick Coghlan)
I was also going to edit the section about
/etc/python/compatibility.cfg, but on further thought I think that's
complicated enough that we should send this to the mailing list and then
raise that for discussion.

More PEP edits

---

pep-513.rst

After mailing list discussion, get rid of the config file and switch to
"import _manylinux" as the way to configure explicit compatibility
settings.

Rewrite the section on detecting platform compatibility

---

pep-513.rst

- All modern 32-bit linux uses linux_i686 for its tag, not
linux_i386. My fault for trusting PEP 425. Confirmed by spinning up a
real CentOS 5 VM in VirtualBox.
- distutils.util.get_platform() uses hyphens; they get normalized to
underscore later. Fix the is_manylinux1_compatible() code to match.

Fix two substantive bugs in the PEP text

---

docker/build_scripts/manylinux1-check.py
pep-513.rst

- Remove the UCS-4 requirement in favor of pip/wheel's new SOABI
support.
- Mandate that manylinux1 extensions *not* link against
libpythonX.Y.so.1, for complicated compatibility-related reasons.
- Update link for the docker images to their new PyPA home.

PEP updates

---

docker/build_scripts/build_utils.sh

This implements one of the changes for the Docker images pursuant to #31, removing `--enable-shared`.

--disable-shared builds in the docker images

---

docker/build_scripts/build.sh

The download redirection for 1.0.2f is in fact broken at the moment: http://openssl.org/source/openssl-1.0.2f.tar.gz
```html
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>404 Not Found</title>
</head><body>
<h1>Not Found</h1>
<p>The requested URL /source/old/1.0.1/openssl-1.0.2f.tar.gz was not found on this server.</p>
<hr>
<address>Apache/2.4.7 (Ubuntu) Server at openssl.org Port 80</address>
</body></html>
```
This works, however: http://openssl.org/source/old/1.0.2/openssl-1.0.2f.tar.gz
But it's best to just update, especially since 1.0.2g is a security release. I verified the signature and hash on 1.0.2g locally.

Update OpenSSL to 1.0.2g

---

README.rst
docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh

`/opt/<major>` links to the UCS-4 builds, but `/opt/<major><soabi_flags>` and `/opt/<full><soabi_flags>` are the more specific paths:
```console
nate@mjolnir0% docker run --rm natefoo/manylinux1_x86_64 ls -l /opt
total 48
lrwxrwxrwx 1 root root  13 Mar  4 17:23 2.6 -> /opt/2.6.9mu/
drwxr-xr-x 1 root root  36 Mar  4 17:24 2.6.9m
drwxr-xr-x 1 root root  36 Mar  4 17:23 2.6.9mu
lrwxrwxrwx 1 root root  12 Mar  4 17:24 2.6m -> /opt/2.6.9m/
lrwxrwxrwx 1 root root  13 Mar  4 17:23 2.6mu -> /opt/2.6.9mu/
lrwxrwxrwx 1 root root  14 Mar  4 17:26 2.7 -> /opt/2.7.11mu/
drwxr-xr-x 1 root root  36 Mar  4 17:27 2.7.11m
drwxr-xr-x 1 root root  36 Mar  4 17:26 2.7.11mu
lrwxrwxrwx 1 root root  13 Mar  4 17:27 2.7m -> /opt/2.7.11m/
lrwxrwxrwx 1 root root  14 Mar  4 17:26 2.7mu -> /opt/2.7.11mu/
lrwxrwxrwx 1 …
```

Add UCS-2 builds of Python to the docker image

---

README.rst
docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/python-tag-abi-tag.py

[this probably doesn't work yet, but I was getting weird "network is unreachable" errors trying to build the image locally -- remember, the great thing about docker build is that it produces identical results no matter where you run it! -- so pushing up to see where travis breaks]
As we are reminded by #38, CPython is not the only implementation of
Python around. This PR doesn't add support for PyPy or anything else,
but it does rearrange things a bit to make room for them.
User visible changes:
- the full-version-number CPython build directories are moved into
/opt/_internal to make clear that users shouldn't rely on the details
of their names. Also, they're called e.g. cpython-2.6.9 now instead of
just 2.6.9.
- The entries in /opt/python/ are now exactly the ABI tags used by each …

Python != CPython

---

docker/build_scripts/build.sh

The path to Python 3.5 has changed; adapt auditwheel install to new
path.

BF: fix auditwheel install for new Python paths

---

docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh

As soon as @matthew-brett's test show that @njsmith's fixes to patchelf are safe, I think we can merge those to the official manylinux docker image.
https://github.com/pypa/auditwheel/pull/25#issuecomment-204806583

Use patchelf 0.9 + Nathaniel's fixes

---

docker/build_scripts/build.sh

```
[root@1301fcc7b9d3 /]# du --si -s /opt/_internal/
1.1G	/opt/_internal/
[root@1301fcc7b9d3 /]# find /opt/_internal -name '*.a' -print0 | xargs -0 rm -f
[root@1301fcc7b9d3 /]# du --si -s /opt/_internal/
802M	/opt/_internal/
[root@1301fcc7b9d3 /]# find /opt/_internal -type f -print0 | xargs -0 -n1 strip --strip-unneeded 2>/dev/null
[root@1301fcc7b9d3 /]# du --si -s /opt/_internal/
695M	/opt/_internal/
[root@1301fcc7b9d3 /]# find /opt/_internal \( -type d -a -name test -o -name tests \) -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) -print0 | xargs -0 rm -f
[root@1301fcc7b9d3 /]# du --si -s /opt/_internal/
341M	/opt/_internal/
```
So this makes /opt/_internal ~3.2x smaller, and shrinks the overall
(unpacked) filesystem from 1.8 GB to 1.1 GB.

Slim down our Python installs

---

docker/Dockerfile-i686
docker/Dockerfile-x86_64
docker/build_scripts/build.sh
docker/build_scripts/ssl-check.py

Use the certifi CA certs bundle

---

docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh

Some URLs not working with older version of curl / SSL - e.g.
curl -LO
https://download.libsodium.org/libsodium/releases/libsodium-1.0.4.tar.gz
See: https://github.com/zeromq/pyzmq/issues/835

NF: build newest curl against newest ssl

---

docker/Dockerfile-i686

Prefixes linux32 command to commands run when doing `docker run img-name
cmd1 cmd2`.
See: https://docs.docker.com/engine/reference/builder/#entrypoint
After this change:
```
$ docker run -ti --rm this_image /bin/bash
bash-3.2# uname -a
Linux a7ea88dd9145 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38
UTC 2016 i686 i686 i386 GNU/Linux
```
Note that passing `linux32` prefix explicitly on the command line, as we
have been doing, is still valid (but has no extra effect):
```
$ docker run -ti --rm this_image linux32 /bin/bash
bash-3.2# uname -a
Linux d41003890ca4 3.10.0-327.13.1.el7.x86_64 #1 SMP Thu Mar 31 16:04:38
UTC 2016 i686 i686 i386 GNU/Linux
```

RF: add linux32 command as entrypoint to image

---

docker/build_scripts/build.sh

Main repositories for CentOS 5 now offline; point yum at
vault.centos.org (via IP to specialize to a particular server).
Maybe fixes gh-100.

BF: use vault repositories for EOL CentOS 5

---

docker/build_scripts/build.sh

This patch has "build.sh" install a recent version of SQLite3 (3.16.2) into /usr/local/lib prior to building all the Pythons.  The motivation is two-fold:
- First, it fixes issue #90, namely that sqlite3 is broken under Python 3.6.
- Second, the version of SQLite3 that comes with Centos5 is *very* old, prior to the signifiant changes of SQLite 3.6.0 which itself was released in mid-2008.  This causes problems when building a Python module that relies on any of these SQLite features, since (a) one can't run the doctests and (b) things like Sphinx's autodoc only work if you can actually import the module.  
I have successfully tested the resulting Docker container by building wheels for [this project](https://bitbucket.org/t3m/snappy).

Use a modern version of SQLite3

---

docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh

Builds patchelf directly from latest source (which needs a newer automake). Fixes #78 and https://github.com/spotify/dh-virtualenv/issues/150, https://github.com/spotify/dh-virtualenv/issues/168, and https://github.com/spotify/dh-virtualenv/issues/203 among others.

Update patchelf from latest master to fix #78

---

docker/build_scripts/build.sh

MRG: Update to openssl 1.0.2l

---

docker/Dockerfile-i686
docker/Dockerfile-x86_64

Saves having to type it in the `docker run` command.
Reference: https://docs.docker.com/engine/reference/builder/#cmd

Specify /bin/bash as the default command

---

docker/build_scripts/build.sh

The centos page on Docker Hub recommends updating packages when using minor tags (e.g., 5.11).

Update centos before doing anything else.

---

docker/deploy.sh

This has apparently been dropped, and they decided that breaking
people was cool because they printed a warning for a while and who
uses docker in unattended workflows lol:
https://github.com/moby/moby/issues/23390
So currently our deploys are broken:
https://travis-ci.org/pypa/manylinux/builds/318363683
This should fix them.

Remove '-e' flag from docker login

---

docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh

Added latest libtool with the same strategy used to add autoconf and automake.

adds latest (2.4.6) libtool to docker images

---

docker/build_scripts/build.sh

It's broken because pip and setuptools have dropped support, and
no-one seems to be bothered or care about fixing it, so let's do this.
Closes #126

Drop support for Python 2.6.

---

docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/py36-requirements.txt
docker/build_scripts/requirements.txt

It might be a good idea to [add hashes](https://pip.pypa.io/en/stable/reference/pip_install/#hash-checking-mode) to packages installed via ```pip```, such as ```certifi``` and ```auditwheel```.
Upside: This should allow a build of ```manylinux``` which uses ```pip``` to detect whether or not packages have been modified against expectations.
Downside: This requires manually updating dependencies (but that might be acceptable in this case, as we do pin down the versions and hashes of many other packages).
This fixes #137.

Enable hash-checking mode for pip install

---

.travis.yml

pyup.io works by creating a branch in the main repo, and then creating
a PR from that branch to master. Travis therefore ends up testing
these commits twice: once because they're a PR, and once because
they're on a branch in the main repo.
This should hopefully disable the branch-based testing, so that we end
up with each PR being tested only once.

Disable Travis "branch builds" for pyup- branches

---

docker/build_scripts/build_utils.sh

I don't know if it's just me, but the previous mirror for downloading the new curl breaks the old curl (error 51: subject name doesn't match host name). This is the easiest, albeit hacky, fix I could find in the meantime. Someone less tired than I am right now should come up with a better fix.

Replace broken(?) curl mirror

---

.gitignore
.travis.yml
docker/Dockerfile-i686
docker/Dockerfile-x86_64
docker/README.rst
docker/build_scripts/build.sh
docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/prefetch.sh
docker/sources/.empty

Also, upgrade OpenSSL to 1.0.2o.
This should avoid problems with using the old tools (e.g. wget) in EL5 to fetch these sources. Since people may do Docker Hub, quay.io, etc. automated builds of their own forks from the Dockerfile/context only, prefetching is not required and if sources are not prefetched we fall back to in-container fetching.
There's a lot more work that can be done to reduce duplication in the build scripts, especially with bash indirect references.
Incorporates/supercedes #172, xref #170, thanks @jcfr

Prefetch source tarballs for OpenSSL and curl outside the docker build context in Travis

---

docker/build_scripts/prefetch.sh

This allows to run the build script from a host that provides bash 3.x (e.g. macOS)

Remove Bash 4.0+ requirement to run prefetch.sh

---

README.rst
docker/build_scripts/build.sh
docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh

This is just to trigger a build and see how it goes.

Add Python 3.7.0b4

---

.travis.yml

This prevents the deploy script to be ran on forks of pypa/manylinux when travis-ci is enabled on those forks.
The deploy script not only fails on forks, it takes up 2x10 minutes  (default timeout) build time on travis-ci infrastructure.

Only run deploy script from pypa/manylinux repository

---

docker/Dockerfile-x86_64
docker/build_scripts/build.sh

1st commit fixes python test removal: around 100MB saved
2nd commit makes x86_64 image based on `centos:5` rather than `centos:5.11`: around 150MB saved

Reduce image size

---

docker/build_scripts/build.sh

The system provided wget utility shall not be used, it's still using the system provided OpenSSL which is too old for most secure downloads (no TLS v1.1/v1.2 support).

Remove wget utility

---

docker/build_scripts/build_env.sh

Fixes 2 low security CVE. c.f. https://www.openssl.org/news/vulnerabilities-1.0.2.html

Update OpenSSL from 1.0.2o to 1.0.2p

---

docker/build_scripts/build_utils.sh

This is just a one-letter change that prevents errors like this one from occurring when an older cURL tarball is still in the directory (eg. when building manylinux incrementally in combination with `prefetch.sh`):
```
+ rm -f curl-7.61.1.tar.gz.sha256
+ tar -zxf curl-7.61.1.tar.gz
+ cd curl-7.60.0.tar.gz curl-7.61.1 curl-7.61.1.tar.gz
build_scripts/build_utils.sh: line 197: cd: curl-7.60.0.tar.gz: Not a directory
```
The issue occurs because `cd curl-*` tries to cd into the tarball.  The trailing slash prevents this by only matching the directory.

Fix error when old curl tarball is in directory

---

build.sh

This allows not to interfere on local system when testing and has no impact on travis-ci build

Do not call docker system prune

---

docker/build_scripts/build_env.sh

Fixes CVE, c.f. https://www.openssl.org/news/cl102.txt

Update OpenSSL from 1.0.2q to 1.0.2r

---

docker/Dockerfile-i686
docker/Dockerfile-x86_64

The idea is that this environment variable could be used as a default value to the --plat argument of auditwheel repair command

Add an AUDITWHEEL_PLAT environment variable

---

README.rst

Hi there,
As mentioned in #179.
I am not sure as `manylinux2010` will be replacing `manylinux1` or we still want to mention `manylinux1` in the readme. 
README should majorly talk about `manylinux2010` and include `manylinux1` briefly
but since `manylinux2010` is in demo phase, would that be a good idea?
Looking for opinions and suggestions.
Thanks
PS: Did a blunder in commit message, fixing it

Including manylinux2010 in readme

---

docker/build_scripts/build_utils.sh

The tarball and the uncompressed directory was not being removed in the
build script.
Resolves: #328

Remove left over libxcrypt files

---

docker/build_scripts/build_env.sh

Update OpenSSL from 1.0.2s to 1.0.2t, fixes security issues

Update OpenSSL from 1.0.2s to 1.0.2t

---

docker/build_scripts/build_env.sh

Update OpenSSL from 1.0.2s to 1.0.2t (manylinux1), fixes security issues

Update OpenSSL from 1.0.2s to 1.0.2t (manylinux1)

---

docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh

Try to use ~3.8.0b4~ 3.8.0rc1 in the manylinux builds
closes #314
closes #313 
replaces #333

include 3.8.0rc1

---

docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh

Repeat gh-344 for the manylinux1 branch

include 3.8.0rc1 in manylinux1

---

.travis.yml
docker/Dockerfile-i686
docker/Dockerfile-x86_64
docker/build_scripts/build.sh

I roughly manage to create a manylinux2010-i686 docker image based on CentOS 6. CentOS 6 is pretty old and i686 doesn't get enough attention so there are a couple of issues to be resolved unlike x86_64.
- There is no i686 devtoolset-8 in SCL so I replaced it with the devtoolsset-7 in cloud linux repo. Having the same version would be the best but 7.3 is still much better than built-in gcc 4.4.
- ~~CentOS 6 has a problem on curl with installed certificates so I have to add "-k" option to curl as a workaround. (I tried to update the existing system certificate but it didn't work)~~
- auditwheel doesn't have a proper list of symbols for i686. [PR](https://github.com/pypa/auditwheel/pull/194) is now ready.
- CentOS 6 32bit doesn't seem to have a vsyscall=emualate issue unlike x86_64 so it can …

Add manylinux2010-i686 docker image

---

docker/build_scripts/py37-requirements.txt

Closes #377 
As mentioned in the `typing` package's documentation, it is meant for older versions of python. The documentation also says is should have NO EFFECT in newer versions of python, this is only true in some cases. The builtin python typing module works fine when called with subprocess, the `typing` package does not. See #377 for more details.
Edit: Should have pointed out that the recommended fix for the error discussed in #377 is to not install the typing package.

Remove external typing package for python 3.7

---

docker/build_scripts/py37-requirements.txt

This library is built into Python 3.6. See #377.

Remove `typing` from manylinux` requirements

---

.travis.yml
README.rst
docker/Dockerfile-s390x
docker/build_scripts/build.sh

Travis-ci now provides s390x support, let's propose a s390x image.

Add s390x support

---

README.rst

This follows issues #393 and #372 which might have been opened due to lack of documentation.

Add a note about python 3.8 ABI dropping the m flag

---

README.rst

Fixes a typo in the readme. `quay.io/pypa/manylinux1_i386` does not exist:
```
$ docker pull quay.io/pypa/manylinux1_i386
Using default tag: latest
Error response from daemon: unauthorized: access to the requested resource is not authorized
$ docker pull quay.io/pypa/manylinux1_i686
Using default tag: latest
latest: Pulling from pypa/manylinux1_i686
8a7625023db4: Already exists
0c59dcf84697: Already exists
7c4b9c038e24: Already exists
74bce53436e1: Already exists
Digest: sha256:1c9cbcb142a60095a074254629af8b8318f1f4f5e1e5a7a98444a58ee66fef4a
Status: Image is up to date for quay.io/pypa/manylinux1_i686:latest
```

Fix link to manylinux1 i686 Docker image

---

docker/build_scripts/build_env.sh

Fixes security issues
This is the last release of OpenSSL 1.0.2 which is now EOL.
Moving to OpenSSL 1.1.1 will require dropping python 3.4

Update OpenSSL from 1.0.2t to 1.0.2u

---

docker/build_scripts/build_env.sh

Fixes security issues
This is the last release of OpenSSL 1.0.2 which is now EOL: https://mta.openssl.org/pipermail/openssl-announce/2019-December/000165.html
Moving to OpenSSL 1.1.1 will require dropping python 3.4

Update OpenSSL from 1.0.2t to 1.0.2u (manylinux1)

---

docker/deploy.sh

Over at cibuildwheel we've been talking about how we might get some determinism in the build process (https://github.com/joerick/cibuildwheel/issues/239), and the manylinux image is one of those things we'd like to lock down.
This PR introduces a docker tag, alongside `latest`, of the format `YYYY-MM-dd-gitsha`, for example `2020-01-18-dea2616`. Each build is tagged, and the tag is pushed to quay.io.
I have tested this on my fork, with Travis building and uploading - see https://quay.io/repository/joerick/manylinux2010_x86_64?tab=tags for how these end up in quay.io.
Thanks!
Fixes #111

Image versioning: Tag each docker build with a unique id, and push that to quay.io

---

docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh

https://bootstrap.pypa.io/get-pip.py does not work anymore for cp34

Use https://bootstrap.pypa.io/3.4/get-pip.py for cp34 (manylinux1)

---

docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh

https://bootstrap.pypa.io/get-pip.py does not work anymore for cp34

Use https://bootstrap.pypa.io/3.4/get-pip.py for cp34

---

docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh

CPython 3.4 has reached EOL in March 2019.
Closes: #427

Remove Python 3.4

---

docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh

OpenSSL 1.0.2 series has reached end-of-life in December 2019
Relates to #429 
Builds on top of #438

Update OpenSSL from 1.0.2u to 1.1.1d

---

docker/build_scripts/build_env.sh

Fixes a security issue: https://www.openssl.org/news/openssl-1.1.1-notes.html

Update OpenSSL from 1.1.1d to 1.1.1e

---

README.rst
docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/py27-requirements.txt
docker/build_scripts/py37-requirements.txt

- document quay.io/organization/pypa for easy reference
- remove 3.4 from the documents
- replace get-pip with ensurepip
- add a hash for wheel
- pin python2.7 requirements since setuptools 46 doesn't support it xref gh-491)

use ensurepip, other small cleanups

---

docker/build_scripts/py27-requirements.txt

Prevent dependabot from upgrading to incompatible versions (hopefully)

Pin py27-requirements.txt to python == 2.7

---

docker/build_scripts/build.sh

(This might also be needed on the other branches.)

Add missing glibc header fixups for __always_inline

---

docker/build_scripts/build_env.sh

[manylinux2010] Update OpenSSL from 1.1.1f to 1.1.1g

---

docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/patches/patchelf-remove-zeroing.diff

This patch is a copy of the upstream PR
https://github.com/NixOS/patchelf/pull/171. This fixes a bug in patchelf
which causes an SONAME entry filled with 'X' values.
This patch in `patchelf`fixes https://github.com/pypa/auditwheel/issues/159 until the patch is applied upstream.

Apply patch in patchelf to avoid zeroing SONAME

---

docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/patches/patchelf-remove-zeroing.diff

This patch is a copy of the upstream PR
https://github.com/NixOS/patchelf/pull/171. This fixes a bug in patchelf
which causes an SONAME entry filled with 'X' values.
Cherry picked https://github.com/pypa/manylinux/commit/052f2ffa38f812608bd549efe8ed1a441e2dd223.

[manylinux1] Apply patch in patchelf to avoid zeroing SONAME

---

docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/patches/patchelf-remove-zeroing.diff

This patch is a copy of the upstream PR
https://github.com/NixOS/patchelf/pull/171. This fixes a bug in patchelf
which causes an SONAME entry filled with 'X' values.
Cherry picked https://github.com/pypa/manylinux/commit/052f2ffa38f812608bd549efe8ed1a441e2dd223.

[manylinux2014] Apply patch in patchelf to avoid zeroing SONAME

---

docker/Dockerfile-i686

The i686 image for manylinux2014 is missing the linux32 entry point resulting in
```
docker run quay.io/pypa/manylinux2014_i686:latest uname -m
```
to return
```
x86_64
```
instead of
```
i686
```
Fix #557

Add linux32 entrypoint on i686 image

---

docker/Dockerfile-i686
docker/build_scripts/build.sh

This PR will bring on i686 a gcc toolchain that's the same as on x86_64.
devtoolset-9 on i686 is rebuilt on `copr` infrastructure in the project [mayeut/devtoolset-9](https://copr.fedorainfracloud.org/coprs/mayeut/devtoolset-9/)
Before this can be merged, I'd like for @pypa/manylinux maintainers to request write access to the `copr` repo so that I'm not the only one with access.
Fix #474

[manylinux2014] Use devtoolset-9 on i686

---

docker/Dockerfile-i686
docker/build_scripts/build.sh

This PR will bring on i686 a gcc toolchain that's the same as on x86_64.
devtoolset-8 on i686 is rebuilt on `copr` infrastructure in the project [mayeut/devtoolset-8](https://copr.fedorainfracloud.org/coprs/mayeut/devtoolset-8/)
Before this can be merged, I'd like for @pypa/manylinux maintainers to request write access to the `copr` repo so that I'm not the only one with access.
Fix #543 
Fix #409

[manylinux2010] Use devtoolset-8 on i686

---

docker/build_scripts/build.sh

Provides backward compatibility with previous builds using `devtoolset-7`.
Use-case: `numpy` caching an `openblas` built with `devtoolset-7` linking with `libgfortran4` rather than `libgfortran5` 
Fix #570

Add libgfortran4 for devtoolset-7 compatibility

---

docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh

With libcrypt.so.1 being removed from the whitelist of auditwheel, system libcrypt.so.1 cannot be grafted as it relies on GLIBC_PRIVATE symbols.
This rebuilds a suitable replacement for libcrypt.so.1
Fix #411
Relates to #305 
Relates to pypa/auditwheel#230

[manylinux2014] Build a libcrypt.so.1 that suitable for grafting

---

docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh

With libcrypt.so.1 being removed from the whitelist of auditwheel, system libcrypt.so.1 cannot be grafted as it relies on GLIBC_PRIVATE symbols.
This rebuilds a suitable replacement for libcrypt.so.1
Fix #411
Relates to #305
Relates to pypa/auditwheel#230

[manylinux2010] Build a libcrypt.so.1 that suitable for grafting

---

docker/build_scripts/build.sh
docker/build_scripts/build_utils.sh

With libcrypt.so.1 being removed from the whitelist of auditwheel, system libcrypt.so.1 cannot be grafted as it relies on GLIBC_PRIVATE symbols.
This rebuilds a suitable replacement for libcrypt.so.1
Fix #411
Relates to #305
Relates to pypa/auditwheel#230

[manylinux1] Build a libcrypt.so.1 that suitable for grafting

---

README.rst

While the README emphasizes manylinux2010 tags as a
result of 40b86fb7f4a77c734c24376231388c1effb11a13,
the mention of manylinux requiring pip >= 19 doesn't
tie itself to a specific manylinux tag, and is
ambiguous especially considering that manylinux1
is still the most common format as of 2020.
This table (taken from the pip changelog at
https://pip.pypa.io/en/stable/news/) makes the
relationship clearer while still allowing the
README to emphasize manylinux2010 in other places.

Specify client-side pip version requirements for tags

---

docker/build_scripts/build.sh

Fixes issue seen in https://github.com/pypa/manylinux/pull/597#issuecomment-628651499 following s390x image update on docker hub.

Fix localedef not being found on s390x image

---

docker/build_scripts/build_env.sh

Changelog: https://docs.python.org/3.9/whatsnew/3.9.html

[manylinux2014] CPython 3.9.0b5 → 3.9.0rc1

---

README.rst

PyPA migrated to travis-ci.com

update travis links to .com

---

docker/build_scripts/build_utils.sh
docker/build_scripts/patches/patchelf-fix-default-aarch64-alignment.patch

Bug reports for Manylinux2014_aarch64 wheels show that they contain bad alignment for Arm distros that use 64k pagesize. This updates patchelf 0.11 to include recent patches that force Arm64 page alignment to 64k regardless of the base system used for building.
Tested locally with the cffi project, resulting wheel and binary after performing audit wheel uses 64k alignment.  Tested wheel on Centos8 on Arm64 and imported cffi with no issue.
Solves Issue: #735

[manylinux2014] arm64 patchelf alignment fix

---

docker/build_scripts/build_env.sh

Changelogs:
* https://docs.python.org/3/whatsnew/changelog.html#python-3-8-6-final
* https://www.openssl.org/news/cl111.txt

[manylinux2010] CPython 3.8.5 → 3.8.6 & OpenSSL 1.1.1g → 1.1.1h

---

docker/Dockerfile-i686
docker/Dockerfile-x86_64
docker/build_scripts/build.sh
docker/glibc/Dockerfile
docker/glibc/Dockerfile-i686
docker/glibc/Dockerfile-x86_64
docker/glibc/build_scripts/CentOS-source.repo

Centos 6 is EOL and is no longer available from the usual mirrors, so switch
to https://vault.centos.org
Fix #836

[manylinux2010 ] Use https://vault.centos.org for yum repos

---

docker/build_scripts/build.sh

Centos 6 is EOL and is no longer available from the usual mirrors, so switch
to archives.fedoraproject.org for EPEL
Fix #843

Use archives.fedoraproject.org for yum EPEL repos on manylinux2010

---

docker/build_scripts/build.sh

OpenSSL on CentOS 5 is old enough that it is starting to break when accessing HTTPS sites. This change updates the yum EPEL repos' `mirrorlist` to only request HTTP mirrors instead of using whatever is returned by default which is starting to cause transient failures when using yum:
```
http://mirror.math.princeton.edu/pub/fedora-archive/epel/5/x86_64/
http://pubmirror1.math.uh.edu/fedora-buffet/archive/epel/5/x86_64/
https://d2lzkl7pfhq30w.cloudfront.net/pub/archive/epel/5/x86_64/
http://mirrors.kernel.org/fedora-buffet/archive/epel/5/x86_64/
https://pubmirror2.math.uh.edu/fedora-buffet/archive/epel/5/x86_64/
https://dl.fedoraproject.org/pub/archive/epel/5/x86_64/
CONNECTED(00000003)
12:error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version:s23_clnt.c:586:
```

Request http mirrors for yum EPEL repos on manylinux1

---

.travis.yml

Travis-CI Graviton 2 builder instances are much faster than LXD containers that were used up until now.
Move base distro from bionic to focal to get support for this.

[manylinux2014] Switch arm64 to using Travis-CI Graviton 2

---

.travis.yml
docker/glibc/Dockerfile
docker/glibc/Dockerfile-i686
docker/glibc/build.sh
docker/glibc/build_scripts/CentOS-source.repo
docker/glibc/build_scripts/glibc.spec.patch
docker/glibc/build_scripts/rebuild-glibc-without-vsyscall.sh
travis-ci/tags.sh

- Update glibc from 2.12-1.212.el6 to 2.12-1.212.el6_10.3
Latest (and last) update to get security fixes for the rebuilt glibc
- Reduce glibc rebuild cache size
2.5GB -> 1GB, should save resources on both local builds and travis-ci builds
- Reduce image size
Final image is now built from scratch because almost everything gets replaced in the base centos:6 image which means it's useless to pull this base image as it will not help with caching but just increase storage/bandwidth requirements when the host does not use centos:6 base image for other images => 384 MB (including centos:6, 194MB) -> 200MB

[manylinux2010] glibc update & glibc cache/image size reduction

---

docker/Dockerfile
docker/build_scripts/build_env_runtime.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/install-libxcrypt.sh
docker/build_scripts/install-runtime-packages.sh

[manylinux2014] Split libxcrypt build in runtime_base image

---

docker/Dockerfile
docker/build_scripts/build_env_runtime.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/install-automake.sh
docker/build_scripts/install-runtime-packages.sh

Builds on top of #879 / #965 / #966 / #967

[manylinux2014] Split automake build in runtime_base image

---

docker/Dockerfile
docker/build_scripts/build-git.sh
docker/build_scripts/build.sh
docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh

Builds on top of #879 / #965 / #966 / #967 / #968 / #969

[manylinux2014] Split git build from build_base image

---

docker/Dockerfile
docker/build_scripts/build-cpython.sh
docker/build_scripts/install-build-packages.sh

Builds on top of #879 / #965 / #966 / #967 / #968 / #969 / #970

[manylinux2014] Split cpython build from build_base image

---

docker/Dockerfile
docker/build_scripts/build-cpython.sh
docker/build_scripts/build-sqlite3.sh
docker/build_scripts/build_env.sh

Builds on top of #879 / #965 / #966 / #967 / #968 / #969 / #970 / #971

[manylinux2014] Split sqlite3 build in build_cpython image

---

docker/Dockerfile
docker/build_scripts/build-cpython.sh
docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/finalize.sh

Builds on top of #879 / #965 / #966 / #967 / #968 / #969 / #970 / #971 / #972

[manylinux2014] Split cpython build by minor version

---

docker/Dockerfile
docker/build_scripts/finalize.sh

Builds on top of #879 / #965 / #966 / #967 / #968 / #969 / #970 / #971 / #972 / #973

[manylinux2014] Hardlink /opt/_internal to save 60MB

---

docker/build_scripts/install-automake.sh
docker/build_scripts/install-libtool.sh
docker/build_scripts/install-libxcrypt.sh
docker/build_scripts/install-patchelf.sh

Builds on top of #879 / #965 / #966 / #967 / #968 / #969 / #970 / #971 / #972 / #973 / #974

[manylinux2014] Strip tools installed in runtime_base image

---

docker/Dockerfile
docker/build_scripts/install-autoconf.sh

Builds on top of #879 / #965 / #966 / #967 / #968 / #969 / #970 / #971 / #972 / #973 / #974 / #975 / #976

[manylinux2014] Update autoconf from 2.69 to 2.70

---

build.sh
docker/Dockerfile
docker/build_scripts/build-cmake.sh
docker/build_scripts/build-git.sh
docker/build_scripts/build-openssl.sh
docker/build_scripts/build-sqlite3.sh
docker/build_scripts/build-swig.sh
docker/build_scripts/finalize.sh
docker/build_scripts/fixup-mirrors.sh
docker/build_scripts/install-autoconf.sh
docker/build_scripts/install-automake.sh
docker/build_scripts/install-build-packages.sh
docker/build_scripts/install-entrypoint.sh
docker/build_scripts/install-libtool.sh
docker/build_scripts/install-libxcrypt.sh
docker/build_scripts/install-patchelf.sh
docker/build_scripts/install-runtime-packages.sh
docker/build_scripts/manylinux-check.py

Builds on top of #879 / #965 / #966 / #967 / #968 / #969 / #970 / #971 / #972 / #973 / #974 / #975 / #976 / #977 / #978

[manylinux2014] Allow manylinux2010 build from manylinux2014 branch

---

.github/workflows/build.yml
.travis.yml
travisci-install-buildx.sh

Now that pypa has some credits on travis-ci again, move back arm64 & s390x on travis-ci where builds are done natively.
ppc64le seems to have trouble with buildx for now so still on GHA

Build arm64 & s390x on travis-ci

---

.github/workflows/build.yml

Seems that QEMU is now used for i686 which slows down the builds.
Only use QEMU when needed.

Only setup QEMU for ppc64le builds on GHA

---

.github/workflows/build.yml
.travis.yml
README.rst
build.sh
docker/Dockerfile
docker/build_scripts/install-build-packages.sh
docker/build_scripts/install-runtime-packages.sh

Contributes to #877 / #542 / #501
Supersedes #822

Add manylinux_2_24 images

---

docker/Dockerfile

Changelogs:
* https://docs.python.org/release/3.6.13/whatsnew/changelog.html
* https://docs.python.org/release/3.7.10/whatsnew/changelog.html
Fixes CVE-2021-23840 and CVE-2021-23841

CPython 3.6.{12→13}, 3.7.{9→10}; OpenSSL 1.1.1{i→j}

---

docker/Dockerfile
docker/build_scripts/build-cmake.sh
docker/build_scripts/build-cpython.sh
docker/build_scripts/build-git.sh
docker/build_scripts/build-openssl.sh
docker/build_scripts/build-swig.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/finalize.sh
docker/build_scripts/install-entrypoint.sh
docker/build_scripts/install-runtime-packages.sh
docker/build_scripts/update-system-packages.sh

- Use hardening for building all tools & libraries
This does not affect the wheels that are produced by end users as proposed in #59 but mitigates potential security issues in the tools used by manylinux images as mentioned in #1005
- Always update system packages in the final step
Since docker cache is used, system packages are not updated when cache is present. Always update them in the final step.

Build hardening

---

docker/build_scripts/install-libxcrypt.sh
docker/build_scripts/update-system-packages.sh

libcrypt is not at the same place on Debian systems.
Update the replacement of libcrypt by libxcrypt so that Debian systems use libxcrypt as well.

Fix libxcrypt install on manylinux_2_24

---

docker/build_scripts/requirements.txt

This adds pypa/build to the requirements file. CC @FFY00 
Closes #940.

feat: add pypa/build

---

docker/build_scripts/requirements.txt

Followup to #941 for manylinux1.

[manylinux1] backport build

---

build.sh
docker/build_scripts/install-runtime-packages.sh
tests/run_tests.sh

Let `ldconfig` know that it should check for libraries in `/usr/local/lib`
This is the default on `manylinux_2_24` but not `manylinux2010`/`manylinux2014`
Fix pypa/manylinux#1022

Fix libcrypt.so.1 not found by some system packages

---

docker/build_scripts/install-runtime-packages.sh
tests/run_tests.sh

Fix _sqlite3 loading the system sqlite version instead of the custom one.
c.f. https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=685706

Fix library search order on manylinux_2_24_i686/aarch64

---

docker/build_scripts/build-sqlite3.sh
tests/ctest/CMakeLists.txt
tests/ctest/test_sqlite3.cpp
tests/run_tests.sh

Previous versions of manylinux2010 included sqlite3 files that allowed downstream dockers to build against the recent version of sqlite3 included in the docker image.  Files include:
- headers `/usr/local/include/{sqlite3.h,sqlite3ext.h}`
- pkgconfig file `/usr/local/lib/pkgconfig/sqlite3.pc`
- libtool file `/usr/local/lib/libsqlite3.la`
- .so file `/usr/local/lib/libsqlite3.so`
PR #972 eliminated these files during cleanup.  This PR restores the above files (which have a relatively small footprint).

sqlite3 headers

---

docker/build_scripts/build.sh

Remove useless kernel-devel-`uname -r` dependency
The package doesn't exist and thus is not installed.
Fix #1056

[manylinux1] Remove useless kernel-devel-`uname -r` dependency

---

docker/build_scripts/update-system-packages.sh
tests/run_tests.sh

Some distros are defining /usr/local/man to be a symlink to /usr/local/share/man
The clean-up done in update-system-packages.sh was a bit too aggressive and lead to breaking the symlink.
Only delete the content of /usr/local/share/man not to break the layout as defined by the distros.
Fix #1060

Do not break /usr/local layout

---

docker/build_scripts/install-runtime-packages.sh

The package mirror favored by manylinux2014 aarch64 builds on travis-ci holds broken metadata.
Add it to the mirror exclusion list to fix the build.

Exclude package mirror with broken metadata

---

.github/workflows/build.yml
.travis.yml
docker/Dockerfile
docker/build_scripts/build-cmake.sh
docker/build_scripts/build-cpython.sh
docker/build_scripts/build-git.sh
docker/build_scripts/build-swig.sh
docker/build_scripts/build_utils.sh
travisci-install-buildx.sh

Now that pypa has some credits on travis-ci again, move back ppc64le on travis-ci where builds are done natively.
- We need to run a rootless docker daemon on ppc64le due to travis-ci LXD configuration but this is better than the
6 hour build on GHA reaching the time limit now & then. We can still go back to QEMU GHA if things prove unstable.
- Disable parallel builds: Given the dockerfile uses multiple unrelated stages & that we're using buildx/buildkit which parallelize those stages, parallelizing builds at each stage does not improve build speed that much and puts too much RAM pressure leading to random failures in CI.
- Workaround GPG issue with ppc64le build: Seems there's an issue with GPG when using the rootless docker daemon,
the import statement and the verify statement must be …

Build ppc64le on travis-ci

---

docker/build_scripts/finalize.sh
tests/run_tests.sh

This is the addition of symlinks mentioned in https://github.com/joerick/cibuildwheel/pull/661; this makes it easier for tools that try to discover multiple Python versions, like Tox/virtualenv/Nox, to use the manylinux images.
A further idea would be to add `python` and `python3` symlinks to a non-system version of Python.

feat: add symlinks to pythonx.y versions

---

docker/build_scripts/finalize.sh
tests/run_tests.sh

Allows for example `pipx install ninja` in a pre-build step, with `ninja` being installed in the PATH.
Other solution would be to expand PATH but this seems messy if someone extends the docker image using non-root user.
Tools from the image (i.e. auditwheel) can't be overwritten without using the `--force` flag i.e. `pipx install --force "auditwheel==3.3.1"`

Make sure pipx installed apps are in the PATH

---

docker/build_scripts/finalize.sh
tests/run_tests.sh

For the sake of consistency when we'll add PyPy in #1103 and given the fact that pipx.y symlinks were introduced very recently, remove those symlinks.
Use `pythonx.y -m pip` instead.

Remove pipx.y symlinks in /usr/local/bin

---

.github/workflows/build.yml
.travis.yml

Those builds are redundant with the PR builds.

Do not build `update-dependencies-pr` branch

---

docker/Dockerfile

Changelog: https://docs.python.org/3.10/whatsnew/3.10.html

chore: bump CPython 3.10.0b1 -> 3.10.0b2

---

.travis.yml
build.sh
travisci-install-buildx.sh

Still default to `docker buildx` frontend
This allows for CI to work again on ppc64le (failing since Travis-CI changed the kernel version)

feat: allow building with docker, docker buildx & buildkit frontends

---

docker/build_scripts/build.sh

fix(manylinux1): pipx wrapper does not handle space in quoted argument

---

docker/build_scripts/finalize.sh
tests/run_tests.sh

The following command-line was not evaluated properly by the pipx wrapper:
`pipx install --pip-args='--no-python-version-warning --no-input' nox`
It errored out with  `pipx: error: unrecognized arguments: --no-input`
It's now handled correctly.

fix: pipx wrapper does not handle space in quoted argument

---

docker/Dockerfile

See: https://www.python.org/downloads/release/python-3100b4/

Update to build against Python 3.10.0b4.

---

docker/Dockerfile

changelog: https://git.savannah.gnu.org/cgit/automake.git/tree/NEWS?h=v1.16.4

chore: automake 1.16.3 → 1.16.4

---

build.sh
docker/build_scripts/install-runtime-packages.sh

chore(manylinux2014): devtoolset 9 → 10

---

docker/build_scripts/build.sh
docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh

changelog: https://github.com/besser82/libxcrypt/blob/v4.4.23/NEWS

chore(manylinux1): libxcrypt 4.4.17 → 4.4.23

---

docker/Dockerfile

pcre 8.45 is the final release of PCRE1 c.f. https://www.pcre.org/original/changelog.txt
No need to add that to the update dependencies script until SWIG allows using PCRE2.

chore: bump pcre 8.44 → 8.45

---

.github/workflows/build.yml
.travis.yml
build.sh
docker/Dockerfile
docker/build_scripts/build-git.sh
docker/build_scripts/build-openssl.sh
docker/build_scripts/build-sqlite3.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/finalize.sh
docker/build_scripts/install-build-packages.sh
docker/build_scripts/install-entrypoint.sh
docker/build_scripts/install-libxcrypt.sh
docker/build_scripts/install-pypy.sh
docker/build_scripts/install-runtime-packages.sh
docker/build_scripts/update-system-packages.sh
tests/run_tests.sh

Add image for musllinux_1_1

---

docker/build_scripts/install-build-packages.sh
docker/build_scripts/install-runtime-packages.sh

With PEP600, more packages are now allowed by auditwheel policies
- libz.so.1
- libexpat.so.1

feat: move zlib-devel & expat-devel from build to runtime packages

---

docker/build_scripts/build.sh

With PEP600, more packages are now allowed by auditwheel policies for manylinux1/manylinux_2_5
- libz.so.1

feat: add zlib-devel to runtime packages

---

docker/build_scripts/build.sh
docker/build_scripts/devtools-2.repo

vault.centos.org / people.centos.org now uses SSL with TLSv1 disabled which is not usable by CentOS 5 yum.
Move to http://archive.kernel.org/centos-vault / http://linuxsoft.cern.ch/cern/devtoolset.

fix: change mirrors

---

docker/build_scripts/build.sh
docker/build_scripts/build_env.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/requirements-tools.txt
requirements-tools.in
update_native_dependencies.py

patchelf 0.14+ requires c++17
c++17 is not available on manylinux1 images, use a prebuilt patchelf wheel for installation.
c.f. #1236 description for the reason for draft.

chore(manylinux1): use PyPI patchelf rather than rebuilding from source

---

docker/Dockerfile
docker/build_scripts/build-cpython.sh
docker/build_scripts/finalize-python.sh

At present, libpythonX.Y.a files are being deleted from the image after the build.  This is a large inconvenience for applications that need it in order to embed the Python interpreter or create a frozen application.  See #91, #793, #255, #30 for use cases.
There are good reasons against including these libraries:
1. The .a files are many megabytes in size each, adding bloat to the images.
2. Broken build systems may link with libpython inadvertently when building extension modules.
3. Users who are not aware that they shouldn't link with libpython for extensions will see libpython and try to link with it.
This PR mitigates all these concerns by compressing all of them into an XZ-compressed tarball:
1. This allows the compression to use a single dictionary, greatly reducing the size.
2. …

Keep libpython static libraries in compressed form

---

docker/build_scripts/install-autoconf.sh
docker/build_scripts/install-automake.sh

These errors show up now & then in CI. This was corrected for OpenSSL build in 1a8f66dc16718b63459c08ea424f4a2d1c95639f  but not for autoconf & automake.

fix: ignore `SIGPIPE` in previous piped command when `head -1` exits

---

docker/build_scripts/build-git.sh
docker/build_scripts/build_utils.sh

While investigating #1222, I found out that some build backends did not forward build args as environment variables so only use those explicitly exposed as environment variables in the scripts.

fix: invalid environment variable used

---

.github/workflows/build.yml
.travis.yml
build.sh
travisci-install-buildx.sh

ppc64le travis-ci seems to be working with the docker-buildx frontend now. on both toronto & saopolo ppc64le workers.
Let's get those builds there (for now)  to remove slow qemu builds from GHA.
Keeping (for now) the (currently) unneeded bits for other frontends to ease future debugs. They've all been tested and work to some extent (depending on worker - saopolo or toronto, the docker one has no cache). I could add a commit to drop them and still be able to find them but don't want to skim through all commits if this is ever needed.

ci: move ppc64le builds back to travis-ci

---

.github/workflows/build.yml
.travis.yml
README.rst
build.sh
docker/build_scripts/build-sqlite3.sh
docker/build_scripts/install-build-packages.sh
docker/build_scripts/install-libxcrypt.sh
docker/build_scripts/install-runtime-packages.sh
docker/build_scripts/update-system-packages.sh
tests/run_tests.sh

fix #1282
Add manylinux_2_28 images based on AlmaLinux 8.
The following architectures are supported:
- `x86_64`
- `aarch64`
- `ppc64le`
`s390x` might be added later on depending on availability of a base image.
`i686` won't be added.

feature: add manylinux_2_28 image

---

docker/build_scripts/install-runtime-packages.sh

`libnsl` has been provided for every manylinux images and is for now whitelisted by auditwheel.
Add it to manylinux_2_28.

Add `libnsl` to manylinux_2_28

---

.github/workflows/build.yml
README.rst
build.sh
docker/Dockerfile
docker/build_scripts/build-cpython.sh
docker/build_scripts/build-git.sh
docker/build_scripts/fixup-mirrors.sh
docker/build_scripts/install-build-packages.sh
docker/build_scripts/install-entrypoint.sh
docker/build_scripts/install-pypy.sh
docker/build_scripts/install-runtime-packages.sh
docker/build_scripts/update-system-packages.sh
tests/run_tests.sh
update_native_dependencies.py

Drop support for manylinux2010

---

docker/Dockerfile
docker/build_scripts/build-tcltk.sh
docker/build_scripts/install-build-packages.sh
docker/build_scripts/install-runtime-packages.sh
update_native_dependencies.py

I'm using manylinux2014 to generate wheels for cx_Freeze. As Tcl/Tk 8.5 is still used, it ended up creating an issue (https://github.com/marcelotduarte/cx_Freeze/issues/1577). So I upgrade to Tcl/Tk 8.6 in the same way as sqlite3.

Add Tcl/Tk 8.6 to manylinux2014

---

.travis.yml
README.rst

AlmaLinux 8.6 now comes with s390x support.
Add a manylinux_2_28_s390x image.

feature: add manylinux_2_28_s390x image

---

docker/build_scripts/install-pypy.sh

This PR restores the `test` module to the PyPy runtimes available in the Docker images, doing for PyPy what #1166 did for CPython

Remove removal of test module (closes #1382)

---

docker/build_scripts/build_env.sh

This reverts commit 2abfe72c69be7cf13b408a23549e15af3d793c8f.
Per https://www.openssl.org:
> 12-Oct-2022 OpenSSL 3.0.6 and 1.1.1r are withdrawn. New releases will be created in due course.

Revert "Bump openssl 1.1.1q → 1.1.1r"

---

docker/build_scripts/install-runtime-packages.sh
tests/run_tests.sh

c.f. https://github.com/pypa/cibuildwheel/pull/1434
GNU tar being used in manylinux images, this also help to get a more consistent environment between the 2 kind of images.

Add GNU tar to musllinux images

---

docker/build_scripts/python-tag-abi-tag.py
docker/build_scripts/requirements3.10.txt
docker/build_scripts/requirements3.11.txt
docker/build_scripts/requirements3.12.txt
docker/build_scripts/requirements3.6.txt
docker/build_scripts/requirements3.7.txt
docker/build_scripts/requirements3.8.txt
docker/build_scripts/requirements3.9.txt
requirements.in
tests/forty-two/forty-two.c
tests/forty-two/pyproject.toml
tests/forty-two/setup.py
tests/run_tests.sh

- tests: build a minimal project with each interpreter
To check we're able to build a minimal project with each interpreter.
- chore: use packaging directly in python-tag-abi-tag.py
Not to depend on an implementation detail of wheel.

Multiple small improvements

---

docker/manylinux-entrypoint

When running with docker on macOS aarch64,
i686 images will use qemu which already defaults to an i686 emulation. This results in the `linux32` command to fail.
Use `linux32` only if `uname -m` reports x86_64.

fix: entrypoint on i686

---

docker/Dockerfile

Python 3.6 & 3.7 do not have support for OpenSSL 3.0.x
In order to move to OpenSSL 3.0.x for Python 3.8+, those older Python (now EOL) will always use the system OpenSSL version rather than the 1.1.1 that was built by manylinux in case the system version was older than 1.1.1
This only impacts manylinux2014 (system OpenSSL is 1.0.2), all other supported base images are using OpenSSL>=1.1.1

chore: use system OpenSSL for Python 3.6 & 3.7

---

docker/Dockerfile
docker/build_scripts/build-openssl.sh
docker/build_scripts/install-build-packages.sh
docker/build_scripts/requirements3.8.txt
docker/build_scripts/requirements3.9.txt
tools/update_native_dependencies.py

move openssl update to 3.0.x branch & run `nox -s update_native_dependencies update_python_dependencies`
Closes #1498
Closes #1536

chore: move openssl update to 3.0.x branch

---

README.rst
build.sh

Add podman to the list of valid frontends and document `MANYLINUX_BUILD_FRONTEND` in the readme.

Add podman to the list of valid build frontends

---

README.rst

docs: add info about musllinux

---

.github/workflows/build.yml
.travis.yml
deploy.sh

xref https://github.com/pypa/cibuildwheel/discussions/1858

chore: deploy with version like tags

---

README.rst

With the move to the perennial naming scheme for new manylinux versions,
it became harder to get a sense for the compatibility implications of choosing
`manylinux_2_28` over `manylinux2014` (for example).
The list of available images is the most straightforward place to maintain a
representative list of notable distro versions that correspond to the
compatibility levels defined by each new manylinux image definition.

Add notable manylinux-compatible distro versions to README

---

docker/build_scripts/manylinux-interpreters.py
docker/build_scripts/python_versions.json
tests/run_tests.sh
tools/update_interpreters_download.py

In order to install GraalPy in the image, one must call `manylinux-interpreters ensure graalpy310-graalpy230_310_native`.
closes #1509

Add GraalPy

---

.github/workflows/build.yml
tests/run_tests.sh

xref https://github.com/pypa/cibuildwheel/issues/1837, https://github.com/astral-sh/uv/pull/3899, https://github.com/astral-sh/uv/pull/3963

test: add minimal test for uv

---

docker/Dockerfile
docker/build_scripts/install-libxcrypt.sh

It's only ever going to be used on manylinux2014 now that manylinux2010 & manylinux_2_24 are out of support.
Only install on manylinux2014 rather than skipping on other policies & remove manylinux2010 perl setup.

Only install libxcrypt on manylinux2014

---

tests/run_tests.sh

Prepare run_tests.sh for manylinux_2_34
This also allows other manylinux-like projects to run the same tests as manylinux without the same number of CPython installations.

feat: prepare run_tests.sh for manylinux_2_34

---

docker/build_scripts/install-runtime-packages.sh
tests/run_tests.sh

feat: use /bin/bash as the default shell

---

README.rst
build.sh
docker/build_scripts/install-runtime-packages.sh

feat: update gcc-toolset to gcc-toolset-13 on manylinux_2_28

---

build.sh
docker/build_scripts/install-runtime-packages.sh

With CentOS 7 having reach EOL, packages versions are now immutable. Using a base image with manylinux runtime packages allows to reduce image size and improve cache efficiency.

chore: use manylinux2014_base base image for manylinux2014

---

tests/run_tests.sh

This reverts commit deca00d9444f6619096a66f7f91058e7000846a8.

Revert "fix(tests): disable uv testing on ppc64le"

---

docker/Dockerfile
docker/build_scripts/build-mpdecimal.sh
docker/build_scripts/build-sqlite3.sh
docker/build_scripts/build-tcltk.sh

CPython will stop embedding mpdecimal. Start building it.
It's only being picked up by cpython 3.13.0 for now.

feat: build mpdecimal for cpython 3.13+

---

.github/workflows/build.yml
.travis.yml
README.rst
build.sh
docker/Dockerfile
docker/build_scripts/build-cpython.sh
docker/build_scripts/build-openssl.sh
docker/build_scripts/build-sqlite3.sh
docker/build_scripts/build-tcltk.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/install-build-packages.sh
docker/build_scripts/install-entrypoint.sh
docker/build_scripts/install-runtime-packages.sh
docker/build_scripts/update-system-packages.sh

towards #1585
close #1575
fix #1338

feat: Add manylinux_2_34 image

---

tests/run_tests.sh

This option is scheduled to be removed in pip 25.1 (pip uses CalVer and this will be Q2 2025):
> **-​-no-python-version-warning**
Deprecated since pip 25.0
([#13154](https://github.com/pypa/pip/issues/13154)) The flag has long done nothing since Python 2 support was removed in pip 21.0. pip has also never warned about deprecations of any other Python version as the flag’s help suggests.
https://ichard26.github.io/blog/2025/01/whats-new-in-pip-25.0/#upcoming-removals
https://github.com/pypa/pip/issues/13154

Remove deprecated `--no-python-version-warning` option

---

README.rst
build.sh

Update base image for musllinux_1_2, this updates the toolchain to gcc 14.

feat: use alpine:3.21 for musllinux_1_2

---

.github/workflows/build.yml
README.rst
build.sh
docker/build_scripts/build-cpython.sh
docker/build_scripts/build-openssl.sh
docker/build_scripts/build_utils.sh
docker/build_scripts/install-build-packages.sh
docker/build_scripts/install-runtime-packages.sh
docker/build_scripts/update-system-packages.sh

This adds an armv7l image that allows to build wheels for armhf (e.g. raspberry Pi).
It was first an experiment in https://github.com/mayeut/manylinux-ubuntu & was tested through https://github.com/pypa/cibuildwheel
It comes with differences compared to other manylinux images so these are explained in the README.
The number of projects publishing wheels for armv7l on PyPI is roughly the same as for ppc64le/s390x, there are already images for those ones.

feat: add manylinux_2_31_armv7l image

---

docker/build_scripts/install-runtime-packages.sh

This makes installing rust easier.
xref https://github.com/pypa/cibuildwheel/issues/2305

feat: add libatomic

---

.github/workflows/multiarch.yml
deploy_multiarch.sh

fix #1306
close #1412
Rather than trying to wait between Travis CI & GHA, there will be a synchronization once every day.

feat: deploy multi-arch images

---

docker/build_scripts/build-cpython.sh
docker/build_scripts/build-sqlite3.sh
docker/tests/ctest/CMakeLists.txt
docker/tests/run_tests.sh

fix #1795
The pkgconfig config file for the custom sqlite is still installed in /usr/local/lib not to break builds finding it this way.
It might break some users but better not to break the system. The custom sqlite3 should really be an internal detail but it was present before so keeping all the `-dev` related files in `/opt/_internal/sqlite3` for now (deprecation to be announced).

fix: hide libsqlite3.so from system search folders

---

.github/workflows/build.yml
README.rst
build.sh
deploy_multiarch.sh
docker/build_scripts/finalize.sh
docker/build_scripts/install-runtime-packages.sh
docker/tests/ctest/CMakeLists.txt

see https://discuss.python.org/t/packaging-support-for-riscv64/58475/9 & https://github.com/pypa/manylinux/discussions/1426#discussioncomment-13753925
fix #1773, only the aarch64 is added while waiting for #1725 to be fixed (& it's probably to early in the ecosystem anyway, having the aarch64 image is also an easier way to debug manylinux_2_39 than the slow qemu manylinux_2_39_riscv64)

feat: manylinux_2_39_aarch64, manylinux_2_39_riscv64 & musllinux_1_2_riscv64
